/**
 * Legacy constants file - maintained for backwards compatibility
 * New code should import directly from @/config modules
 * @deprecated Use imports from @/config instead
 */

import {
  CANVAS_CONFIG,
  PHYSICS_CONFIG,
  GAME_RULES,
  RENDERING_CONFIG,
  ENTITY_SIZES,
  COIN_PHYSICS,
  COIN_SPAWNING,
  COIN_EFFECTS,
  BOMB_POINTS,
  MULTIPLIER_SYSTEM,
  BONUS_POINTS,
  COLORS,
  DEFAULT_AUDIO_SETTINGS,
  DEV_CONFIG,
} from "@/config";

// Re-export for backwards compatibility
export { COLORS, DEFAULT_AUDIO_SETTINGS, DEV_CONFIG };

// Legacy GAME_CONFIG object - assembled from new config modules
// Maintained for backwards compatibility with existing code
export const GAME_CONFIG = {
  // Canvas
  CANVAS_WIDTH: CANVAS_CONFIG.WIDTH,
  CANVAS_HEIGHT: CANVAS_CONFIG.HEIGHT,
  
  // Entity sizes
  PLAYER_HEIGHT: ENTITY_SIZES.PLAYER.HEIGHT,
  PLAYER_WIDTH: ENTITY_SIZES.PLAYER.WIDTH,
  BOMB_SIZE: ENTITY_SIZES.BOMB_SIZE,
  MONSTER_SIZE: ENTITY_SIZES.MONSTER_SIZE,
  PLATFORM_HEIGHT: ENTITY_SIZES.PLATFORM_HEIGHT,
  COIN_SIZE: ENTITY_SIZES.COIN_SIZE,
  
  // Rendering
  USE_SPRITES: RENDERING_CONFIG.USE_SPRITES,
  USE_BOMB_SPRITES: RENDERING_CONFIG.USE_BOMB_SPRITES,
  PARALLAX_ENABLED: RENDERING_CONFIG.PARALLAX_ENABLED,
  
  // Physics
  GRAVITY: PHYSICS_CONFIG.GRAVITY,
  FLOAT_GRAVITY: PHYSICS_CONFIG.FLOAT_GRAVITY,
  FAST_FALL_GRAVITY_MULTIPLIER: PHYSICS_CONFIG.FAST_FALL_GRAVITY_MULTIPLIER,
  MOVE_SPEED: PHYSICS_CONFIG.MOVE_SPEED,
  JUMP_POWER: PHYSICS_CONFIG.JUMP_POWER,
  SUPER_JUMP_POWER: PHYSICS_CONFIG.SUPER_JUMP_POWER,
  
  // Coin physics
  COIN_BOUNCE_SPEED: COIN_PHYSICS.BOUNCE_SPEED,
  COIN_BOUNCE_DAMPING: COIN_PHYSICS.BOUNCE_DAMPING,
  COIN_GRAVITY: COIN_PHYSICS.GRAVITY,
  
  // Jump mechanics
  MIN_JUMP_DURATION: PHYSICS_CONFIG.MIN_JUMP_DURATION,
  MAX_JUMP_DURATION: PHYSICS_CONFIG.MAX_JUMP_DURATION,
  
  // Game rules
  TOTAL_BOMBS: GAME_RULES.TOTAL_BOMBS,
  STARTING_LIVES: GAME_RULES.STARTING_LIVES,
  
  // Coin spawning rules
  POWER_COIN_SPAWN_INTERVAL: COIN_SPAWNING.POWER_COIN_SPAWN_INTERVAL,
  BONUS_COIN_SPAWN_INTERVAL: COIN_SPAWNING.BONUS_COIN_SPAWN_INTERVAL,
  EXTRA_LIFE_COIN_RATIO: COIN_SPAWNING.EXTRA_LIFE_COIN_RATIO,
  
  // Coin effects
  POWER_COIN_DURATION: COIN_EFFECTS.POWER_COIN_DURATION,
  POWER_COIN_POINTS: COIN_EFFECTS.POWER_COIN_POINTS,
  MONSTER_KILL_POINTS: COIN_EFFECTS.MONSTER_KILL_POINTS,
  
  // Coin base points
  BONUS_MULTIPLIER_COIN_POINTS: COIN_EFFECTS.BONUS_MULTIPLIER_COIN_POINTS,
  EXTRA_LIFE_COIN_POINTS: COIN_EFFECTS.EXTRA_LIFE_COIN_POINTS,
  
  // Multiplier system
  MULTIPLIER_THRESHOLDS: MULTIPLIER_SYSTEM.THRESHOLDS,
  MAX_MULTIPLIER: MULTIPLIER_SYSTEM.MAX_MULTIPLIER,
  
  // Scoring
  BOMB_POINTS: BOMB_POINTS,
  
  // Bonus points
  BONUS_POINTS: BONUS_POINTS,
} as const;
